version: '2'

services:
  nginx:
    image: docker.io/matheusbsilva/nginx-tropical-hazards:latest
    ports:
      - "80:80"
    links:
      - web
      - db
      - mongo
  db:
    image: postgres
    ports:
      - "5432:5432"
  web:
    image: docker.io/matheusbsilva/tropical-hazards-api:latest
    command: /bin/sh boot.sh 
    ports:
      - "8000:8000"
    links:
      - db
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
